

FROM golang:1.26-alpine AS build
WORKDIR /app
COPY . .

RUN CGO_ENABLED=0 go build -o /servidor ./cmd/servidor

FROM alpine:latest
COPY --from=build /servidor /servidor

EXPOSE 8080

ENTRYPOINT ["/servidor"]
